### PR TITLE
Allow --patients to consume text files with IDs in it

### PR DESCRIPTION
**Pull request by mikix**
This allows `--patients` to be passed either an NDJSON file (and I also had it scan for [JSON Lines](https://jsonlines.org/) files whynot) or a text file that it will scan for one ID per line.

This is helpful when you have a non-Group-based cohort that you want to crawl.

I also added a commit to drop the old typescript config file, since I personally found it confusing to have both in the repo still. But if you want me to keep that file going, happy to add it back.

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
Code changes look great! However, I don't understand why the example config had to be removed. Its purpose is to help first-time users get started quickly by copying it and then modifying it as needed. That is also explained in the README. I think you will have to restore it, unless you have better idea of how this can be done.

**Comment by mikix** [comment]
> However, I don't understand why the example config had to be removed.

Your confusion is a perfect example of why that file should be removed. I deleted the old (no longer referenced) v1 config (`./config/example-config.ts`) not the modern recommended v2 configuration file (`./example-config.js`). Having both is confusing, especially since we don't really support the v1 format.

**Comment by vlad-ignatov** [comment]
Oh yes! I can't remember how I've ended up with two files 👍 

Can you also remove [this](https://github.com/smart-on-fhir/fhir-crawler/blob/main/.gitignore#L109) line and it should be ready to merge

**Comment by mikix** [comment]
> Can you also remove [this](https://github.com/smart-on-fhir/fhir-crawler/blob/main/.gitignore#L109) line and it should be ready to merge

Done :+1: (arguably, the config/* line could also go, since that's no longer a folder we ship/encourage anyone to use, but it's harmless)

**Comment by vlad-ignatov** [comment]
Yeah..., I am using ./config/ to store my private config files. I recommend people use a folder outside the project to avoid adding secrets to git, but I don't follow my own example because it is slightly less messy this way (easier to find things after you've forgotten what goes where...). So lets just keep that for now. Thanks!

**Pull request merged**
